---
# tasks file for install_grafana

- name: Install required packages
  package:
    name: "{{ item }}"
    state: present
  loop:
    - apt-transport-https
    - software-properties-common
    - wget

- name: Add Grafana GPG key
  apt_key:
    url: https://apt.grafana.com/gpg.key
    state: present

- name: Add Grafana APT repository
  apt_repository:
    repo: "deb https://apt.grafana.com stable main"
    state: present

- name: Update apt cache
  apt:
    update_cache: yes

- name: Install Grafana package
  package:
    name: grafana
    state: present

